steps:
  - name: gcr.io/cloud-builders/docker
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/${_ENV}:${SHORT_SHA}", "-t", "gcr.io/$PROJECT_ID/Sample-${_ENV}:${$TAG_NAME}", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/${_ENV}"]:

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "Sample-${_ENV}",
        "--image",
        "gcr.io/$PROJECT_ID/${_ENV}:${SHORT_SHA}",
        "--region",
        "europe-west1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]
