steps:
# build image:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag'
  - '${_IMAGE_NAME}:$SHORT_SHA'
  - '--tag'
  - '${_IMAGE_NAME}:latest'
  - '.'
#start the container for sanity check
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'run'
  - '-d'
  - '--name'
  - 'sanity-check'
  - '${_IMAGE_NAME}:$SHORT_SHA'

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    sleep 10
    if docker exec sanity-check pgrep -f "gunicorn" >/dev/null; then
      echo "Cont & server started"
    else
      echo "Sanity check failed"
      exit 1
    fi

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'rm'
  - '-f'
  - 'sanity-check'


# push image:
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '--all-tags', '${_IMAGE_NAME}']

#only cloud logs
options:
  logging: CLOUD_LOGGING_ONLY

